
* Features

** TODO Support saving the state of the units

*** Why
    Support saving the current state of the unit factories so that

*** How
    Probably by enabling some sort of serialization in the units and dimensions.

*** Analysis
    A nice additional feature will be that it will be possible to store unit choices.


** TODO Support non dimensional units

*** Why
    For some physical constants or values that have no dimension.

*** How
    Probably just have two singletons, something like:

    - NonDimensionalUnit :: a "fake" unit that has a VoidDimension as dimension;
    - VoidDimension :: this would be the "a dimensional" dimension. It's only unit would be the NonDimensionalUnit.


** TODO Proper time support

*** Why
    To have proper conversion between Time units.

*** How
    Probably by using java.util.Date or maybe providing a option to use with JodaTime.


** TODO simplification of quotient units

*** Why
    To make quotient units simpler.
*** How
    Probably by removing units that cancel one another in the quotient.
*** Analysis
    - Removing units from a product unit will lead to the creation of a new dimension;
    - We'll need to deal with simplifications where the divisor becomes empty and we would return a unit product or even a single base unit.


* Support

** TODO Upload artifacts to a mvn repository

** TODO Upload api docs to github pages after each build
